services:
  - type: web
    name: ppe-detection
    env: docker
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t ppe-detection .
    startCommand: docker run -p $PORT:8000 ppe-detection
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: ppe-db
          property: connectionString

databases:
  - name: ppe-db
    plan: free 