# Generated by Django 5.2.2 on 2025-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detection_results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
