apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppe-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ppe-detection
  template:
    metadata:
      labels:
        app: ppe-detection
    spec:
      containers:
      - name: ppe-detection
        image: ppe-detection:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_DEBUG
          value: "False"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        volumeMounts:
        - name: static-files
          mountPath: /app/staticfiles
        - name: media-files
          mountPath: /app/myapp/media
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: static-files-pvc
      - name: media-files
        persistentVolumeClaim:
          claimName: media-files-pvc
