version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 demo.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/myapp/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False

volumes:
  static_volume:
  media_volume:
