# Generated by Django 5.2.2 on 2025-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='processed_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
